<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-05-15T15:37:59 IST" name="Default suite" finished-at="2022-05-15T15:38:13 IST" duration-ms="13791">
    <groups>
    </groups>
    <test started-at="2022-05-15T15:37:59 IST" name="Default test" finished-at="2022-05-15T15:38:13 IST" duration-ms="13791">
      <class name="Scenario_component.Login_rediff">
        <test-method is-config="true" signature="runFirst()[pri:0, instance:Scenario_component.Login_rediff@36fc695d]" started-at="2022-05-15T15:37:59 IST" name="runFirst" finished-at="2022-05-15T15:37:59 IST" duration-ms="10" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runFirst -->
        <test-method is-config="true" signature="launchApp()[pri:0, instance:Scenario_component.Login_rediff@36fc695d]" started-at="2022-05-15T15:38:00 IST" name="launchApp" finished-at="2022-05-15T15:38:03 IST" duration-ms="3303" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
        <test-method signature="test_Invalid_login(java.util.Map)[pri:0, instance:Scenario_component.Login_rediff@36fc695d]" started-at="2022-05-15T15:38:03 IST" name="test_Invalid_login" data-provider="dp_Invalidlogin" finished-at="2022-05-15T15:38:07 IST" duration-ms="3962" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{UNAME=qtwor1, TC_ID=GB_01, ORDER_SET=1.0, SCRIPT_NAME=Invalid, EXECUTE_FLAG=Y, PWD=learn123, EXP_RESULT=Sorry we were unable to complet}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
failed and expected result is Sorry we were unable to complet and actual result is Sorry we were unable to complete this step because :]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
failed and expected result is Sorry we were unable to complet and actual result is Sorry we were unable to complete this step because :
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at Scenario_component.Login_rediff.test_Invalid_login(Login_rediff.java:55)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_Invalid_login -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:Scenario_component.Login_rediff@36fc695d]" started-at="2022-05-15T15:38:07 IST" name="teardown" finished-at="2022-05-15T15:38:07 IST" duration-ms="193" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="launchApp()[pri:0, instance:Scenario_component.Login_rediff@36fc695d]" started-at="2022-05-15T15:38:07 IST" name="launchApp" finished-at="2022-05-15T15:38:10 IST" duration-ms="2670" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
        <test-method signature="test_Invalid_login(java.util.Map)[pri:0, instance:Scenario_component.Login_rediff@36fc695d]" started-at="2022-05-15T15:38:10 IST" name="test_Invalid_login" data-provider="dp_Invalidlogin" finished-at="2022-05-15T15:38:13 IST" duration-ms="2919" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{UNAME=qtpworld2008@gmail.com, TC_ID=GB_02, ORDER_SET=1.0, SCRIPT_NAME=Invalid, EXECUTE_FLAG=Y, PWD=lop123, EXP_RESULT=Sorry we were unable to complete this step because :}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_Invalid_login -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:Scenario_component.Login_rediff@36fc695d]" started-at="2022-05-15T15:38:13 IST" name="teardown" finished-at="2022-05-15T15:38:13 IST" duration-ms="125" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="runLast()[pri:0, instance:Scenario_component.Login_rediff@36fc695d]" started-at="2022-05-15T15:38:13 IST" name="runLast" finished-at="2022-05-15T15:38:13 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runLast -->
      </class> <!-- Scenario_component.Login_rediff -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
